### ISSUE TITLE
Filter out Contemporary keywords[labels] ?

### ISSUE THREAD

**Issue by iwada** [iharsuvorau/ml-2021-ajapaik#10]
As Per Partner's request -  mobile phones didn't exist in the '60s unless someone time traveled.

 If needed eventually.

**Comment by iwada** [comment]
@hallibay We've decided to stick with what the COCO dataset offers.

**Comment by hallibay** [comment]
> @hallibay We've decided to stick with what the COCO dataset offers.

Alright
