### ISSUE TITLE
Implement a command line tool for Object Detection with YOLO

### ISSUE THREAD

**Issue by iwada** [iharsuvorau/ml-2021-ajapaik#17]
Idea is to wrap the YOLO functionality around a command-line tool. 

**Inputs** 

- image_path
- threshold flag
- dataset(COCO(default), Imagenet,...)
- ...

**Output**

- A File(s) containing bounds of bounding boxes of detected images
- ...

**Comment by iharsuvorau** [comment]
@iwada @hallibay any news?

I refactored the code of this repository and put the image area (or picture-in-picture) detection into `pip_detector` folder. So you can upload your code into a separate folder as well, so we have our repository organized. At the end we need 2 CLI-tools. You also can have a look at how I implemented CLI-interface, if you have any doubts. But you're free to do it however you like.

**Comment by iwada** [comment]
Would much further changes to what we have there in the coming hours
